name: exatrkx-hsf

channels:
    - rapidsai
    - nvidia
    - pytorch
    - pyg
    - conda-forge

dependencies:
    - pip
    - numpy
    - pandas
    - scipy
    - matplotlib
    - cupy
    - cudatoolkit=11.3
    - pytorch==1.10.2
    - pytorch-lightning
    - pyg
    - faiss-gpu
    - cudf=21.12
    - cugraph=21.12
    