# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/embedding_processed/1GeV_cut_barrel/train
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_GravMetric_Study_E
model: MultiGravAGNN
gpus: 3

# ----------- Dataset parameters
pt_signal_cut: 1000.
pt_background_cut: 1000.
nhits: 3.
primary_only: True
train_split: [800, 80, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# ------------ Training parameters
lr: 0.001
factor: 0.7
patience: 100
regime: [rp, ci, hnm, norm]
max_epochs: 400
scheduler: step
working_points: [99, 98, 95] # Need to list in decreasing efficiency

output_k: 30
output_r: 0.1
output_weight: 4
output_margin: 0.1
randomisation: 1
points_per_batch: 300000
warmup: 1

# ------------ MODEL PARAMETERS --------------
# ------------ MLP Parameters 
spatial_channels: 3
cell_channels: 11
feature_hidden: 64
attention_heads: 4
nb_layer: 3
emb_dim: 12
activation: SiLU
layernorm: True 
batchnorm: True 

# ------------- GNN Parameters
n_graph_iters: 8
hidden_norm: True 
emb_norm: True 