input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/hetero_processed/0GeV_v3
output_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/hetero_gnn_processed/0GeV_v3
artifacts: /global/cfs/cdirs/m3443/data/lightning_models/lightning_checkpoints
project: ITk_Toy_HeteroGNN
model: HeteroGNN
gpus: 1
nodes: 1

# Dataset parameters
pt_background_cut: 100.
pt_signal_cut: 1000.
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [200, 20, 10] # Number of [training, validation, testing] examples
sorted_events: False
endcaps: True
true_edges: modulewise_true_edges
noise: True

# Model parameters
edge_cut: 0.5
hidden: 64
spatial_channels: 3
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
batchnorm: True
aggregation: sum_max
hidden_activation: SiLU
# output_activation: Tanh
model_ids: 
  - {"volume_ids": [0, 1], "num_features": 3}
  - {"volume_ids": [2], "num_features": 9}
  - {"volume_ids": [3], "num_features": 9}
hetero_level: 0
recurrent: False
concat_output: True
weight: 1
warmup: 3
lr: 0.002
factor: 0.9
train_purity: 0
patience: 10
truth_key: pid_signal
mask_background: True
max_epochs: 100